### ISSUE TITLE
Deploying Smart Contracts hangs, takes your money but just do nothing. Transaction fees should be refundable when a contract creation fails

### ISSUE THREAD

**Issue by artemisone-org** [crypto-org-chain/cronos#400] opened 2022-03-18 14:25 UTC
Hello,

At the moment I have been trying to deploy the contracts I have been working on to mainnet. I have lost probably around 2,000 USD trying to get somewhere with this network but it just seems to fall on deaf ears. 

Basically deploy a modest sized contract. And if you are lucky it deploys if not then bad luck your money is gone with absolutely no trace of it. 

I already feel the pains of any developer trying to do something on this network and fail to do so because the network just keeps taxing you more and more money on the transaction fees with no way to get a refund.

**Comment by yihuang** [comment] 2022-03-18 15:39
https://rpc-cronos.crypto.org/tx_search?query=%22ethereum_tx.ethereumTxHash=%270x9fd351953d4085b54efb5003c865c59cad945affa1f970ebb971387d59bf808b%27%22

I take your latest contract deploy tx hash and checked the error message with above url, it shows: `contract creation code storage out of gas`. so it's indeed an out of gas issue.
Unfortunately, there's indeed this gas refund issue on mainnet(https://github.com/crypto-org-chain/cronos/issues/221), it's fixed in next version, because it's a consensus breaking change, so have to wait for the next breaking upgrade, hopefully early Apirl.
My suggestion is always use estimate gas to get the accurate gas limit first for now.

**Comment by artemisone-org** [comment] 2022-03-18 17:06
It is using the gas estimate I tested in different ways. 

- Raising the gas price 
- Letting it do it itself. Which at the end of the day is the same it would either get the tx make it look like a success. And it would also most of the time just "hang" and take the fees.

**Comment by yihuang** [comment] 2022-03-18 17:08
Can you share the tx object so I can try to reproduce it locally?

**Comment by yihuang** [comment] 2022-08-18 03:47
There were unlucky tx scenarios where tx fee is deducted while can't be found in json-rpcs, I believe they are already fixed in v0.7.x upgrade, closing now, feel free to reopen if it happens again.

**Closed by yihuang** 2022-08-18 03:47 UTC
