### ISSUE TITLE
Problem: cronosd status shows "dial tcp: lookup localhost: device or resource busy"

### ISSUE THREAD

**Issue by artemisone-org** [crypto-org-chain/cronos#469] opened 2022-05-11 00:57 UTC
**Describe the bug**
Currently using the latest binaries using `rocksdb` as backend. At the moment there's a weird behavior where I can't query the status of the server through the binary.

I can `wget -X POST [URL]` and it shows me the usual

![image](https://user-images.githubusercontent.com/95833113/167747805-734b03f8-4253-44b9-a07a-ea857eca0379.png)

![image](https://user-images.githubusercontent.com/95833113/167747870-0f9e6498-d627-410c-9eb3-9b667fd4ccc9.png)

**To Reproduce**
1. Download rocksdb binary of cronos
2. run it, unsure if it will reproduce but my node is fully synced, do `cronosd status`
3. See error

**Comment by yihuang** [comment] 2022-05-11 01:14
which version? can you show me the `cronosd version --long`?

**Comment by artemisone-org** [comment] 2022-05-11 01:57
> which version? can you show me the `cronosd version --long`?

```cronos:~$ cronosd version --long
name: cronos
server_name: cronosd
version: v0.7.0
commit: 799ac47
build_tags: ledger,cgo,mainnet,rocksdb
go: go version go1.17.5 linux/amd64
build_deps:
- '@(devel)'
cosmos_sdk_version: ""```

**Comment by yihuang** [comment] 2022-05-11 02:53
can you follow the diagnostic instructions here: https://unix.stackexchange.com/a/604422, looks like system dns resolver issue.

**Comment by artemisone-org** [comment] 2022-05-11 17:45
Hello,

Adding up as this might be impacting new nodes. 

<img width="1628" alt="image" src="https://user-images.githubusercontent.com/95833113/167913349-9011f020-6109-40db-a78a-4baab7feb7f3.png">

Same binaries as I posted. The difference is that this is a brand new install of Ubuntu on the server after a hardware failure and all I did was restore the data folder...

**Comment by yihuang** [comment] 2022-05-11 22:18
I'm not sure of the root cause, but one thing you can try is to build a cronosd with the `netgo` tag, it use a different dns resolver implementation. to build a rocksdb version (the makefile version has `netgo` tag by default):
```
$ COSMOS_BUILD_OPTIONS=rocksdb make build
```

**Comment by artemisone-org** [comment] 2022-05-11 22:41
I'll give it a try. I guess the only thing that has me scratching my head is that the binaries in terms of file size have been greatly reduced and I don't know if the new builds are stripping things out that aren't supposed to be stripped. (used to be 113 and now it is just 34mb for it to be ran bare minimum) . I also noticed the folder structure changing a bit as well... so... all in all I don't know if that could narrow it down for somebody but I'm not really familiar with golang itself as a language.

**Comment by samuel-tay** [comment] 2022-05-16 12:41
Hi, I have this issue too.

The problem is with precompiled rocksdb version not recognizing localhost for some reason. 'localhost' doesn't work when used in app.toml, config.toml, and client.toml.

The workaround is to use 127.0.0.1. This doesn't exist in goleveldb version.

I've reported this in cronos-validators chat as well.

**Comment by yihuang** [comment] 2022-05-17 01:15
Can you post the exact linux distribution version that you use, let me see if I can reproduce it.

**Comment by yihuang** [comment] 2022-05-17 03:43
I've reproduced this issue, and found two ways to work around the issue:
- Set ld path to refer to system library directory:
  ```
  $ export LD_LIBRARY_PATH=/chain/.cronosd/cosmovisor/genesis/lib:/usr/lib/aarch64-linux-gnu
  ```
- Use the golang resolver:
  ```
  $ export GODEBUG=netdns=go
  ```

hopefully we can fix the root cause in next release.

**Comment by yihuang** [comment] 2022-05-19 06:38
fixed by https://github.com/crypto-org-chain/cronos/pull/476.
The `v0.7.x` released binaries won't have this issue.

**Closed by yihuang** 2022-05-19 06:38 UTC
