### ISSUE TITLE
Problem: wrong Block.Header.AppHash crashes

### ISSUE THREAD

**Issue by hpmv** [crypto-org-chain/cronos#284] opened 2021-12-29 19:14 UTC
**Describe the bug**
My node once in a while crashes with errors like this:
```
panic: Failed to process committed block (780414:CF2396E752FF8BD24E64AB4F926EB4B2EB488AB070611DFD29F1EFB8AA45B9A0): wrong Block.Header.AppHash.  Expected FB6CC3B73190529D528E5EB3│································
18CBA4FB1E47D48030C952A47C6E2429958F4E29, got 6875B5CB3A6F7FD9C1AC10FE1F16D4DD5A6CE28727408669C4254E36F3A4B351
```

restarting the node gives a similar error.

**To Reproduce**
Cannot reproduce reliably other than running the node and this might happen once in a couple of days. I'm using version v0.6.1.

**Expected behavior**
App really should recover from such errors by automatically reverting to the previous height. Or, a manual tool like state_recover from BSC would also be great. Right now there's no solution other than recovering from a disk backup.

Could a dev tell me how to revert back to the previous height manually via setting leveldb keys? I know I need to set a couple of keys in the Tendermint side, but the app side is too confusing to dig in for me. Thanks!

**Comment by tomtau** [comment] 2021-12-30 01:20
@hpmv Thanks for reporting the issue. For the wrong app hash error, it'd be helpful if you could provide more details: which block heights, which network (I assume the mainnet beta?), etc. this happens on. Given it was on v0.6.1, it could also be the case that there were some unnoticed consensus state breaking changes between 0.6.1 and 0.6.5.

The latest Tendermint has a rollback feature, but it hasn't been used in Cosmos SDK yet: https://github.com/cosmos/cosmos-sdk/issues/10281

@yihuang @JayT106 may advise if there's a manual workaround in the meantime.

**Comment by hpmv** [comment] 2021-12-30 04:40
Thanks @tomtau! The network is mainnet beta, and the height was as shown in the error message: 780414. I just got it again at another height 789757.

What's the version (commit hash) that's supposed to be running in Mainnet beta?

**Comment by JayT106** [comment] 2021-12-30 04:53
@hpmv you might try to reset the DB state via modifying the [wal](https://github.com/tendermint/tendermint/blob/master/docs/nodes/running-in-production.md#wal-corruption), remove the latest messages until the previous `EndHeight #` message. Be careful to back up your data first when using it.

However, it is not guaranteed work due to the unknown root cause of the appHash crashes.  We need more investigations to understand the issue.

**Comment by hpmv** [comment] 2021-12-30 04:55
Thanks Jay! Is this a known issue in the community (I see a previous bug filed about this too)?

**Comment by tomtau** [comment] 2021-12-30 05:17
ok, it seems this may be a duplicate issue: https://github.com/crypto-org-chain/cronos/issues/256
That issue was with 0.6.4. It may be also be due to non-deterministic operations, so it could happen irrespective of changes between 0.6.1 and 0.6.5

**Comment by yihuang** [comment] 2022-03-08 03:14
we observed this in one of our RPC nodes after upgrading to 0.6.6, after inspecting and comparing the iavl storage using iaview tool, we found that [this transaction](https://cronos.org/explorer/tx/0x78a1e2eae2f6ed60f5b9e013adf2e85b04887197ef639017e73875cca79d66f7/token-transfers) is reverted on the problematic node(and balance deducted with "gas limit * gas price", but it's successfully executed on the normal nodes.

**Comment by JayT106** [comment] 2022-03-08 16:35
> we observed this in one of our RPC nodes after upgrading to 0.6.6, after inspecting and comparing the iavl storage using iaview tool, we found that [this transaction](https://cronos.org/explorer/tx/0x78a1e2eae2f6ed60f5b9e013adf2e85b04887197ef639017e73875cca79d66f7/token-transfers)'s sender's balance is different between the problematic node and normal node, and the numbers match the hypothesis that the tx is reverted on the problematic node(and the sender's balance is deducted by "gas limit * gas price"), but successfully executed on the normal nodes.

Is the PR https://github.com/crypto-org-chain/cronos/pull/377 the root cause of the AppHash mismatch in 0.6.6?

**Comment by JayT106** [comment] 2022-03-11 15:36
@hpmv , what's your setup for `fast_sync=` and `statesync.enable=`, trying to reproduce this, it would be great if you can provide it. Thanks.

**Comment by JayT106** [comment] 2022-04-05 18:20
From investigating the recent crashes cases, suspect the EVM module might cause the indeterministic result. But we need more crashed databases to confirm.

**Comment by yihuang** [comment] 2022-04-19 09:28
the app hash mismatch issue has been fixed, closing now.

**Comment by yihuang** [comment] 2022-05-03 09:16
> App really should recover from such errors by automatically reverting to the previous height. Or, a manual tool like state_recover from BSC would also be great. Right now there's no solution other than recovering from a disk backup.

This rollback command may help in the future: https://github.com/cosmos/cosmos-sdk/pull/11361

**Comment by yihuang** [comment] 2022-05-26 08:35
https://github.com/cosmos/cosmos-sdk/issues/12012

We believe the root cause is found, and the workaround for now is to increase the file open limit using `ulimit`.

**Closed by yihuang** 2022-05-26 08:35 UTC
