### ISSUE TITLE
can‘t connect to ws server in v0.7.0

### ISSUE THREAD

**Issue by huahuayu** [crypto-org-chain/cronos#500] opened 2022-05-21 08:28 UTC
## Env

cronos: 0.6.5 and 0.7.0

## Issue

Can't subscribe newHead and newTxs:

SubscribeNewHeads / newTxs from golang

```text
dial tcp <my_ip>:8546: connect: connection reset by peer ws://<my_ip>:8546
```

Subscribe from `wscat`

```text
wscat -c ws://<my_ip>:8546
error: connect ECONNRESET <my_ip>:8546
```

## Behavior in v0.6.5

You can connect to ws after restarting, it works only 5-10 mins, then you get error and need another restart. 

## Behavior in v0.7.0

Today I upgrade to v0.7.0, the longest record I have is about 1 hour, within that 1 hour, I can subscribe newHead and newTx, I test it many times, so I thought it is been fixed in v0.7.0. 

But when I tried again just now, I can't connect ws server anymore.  Even restarting cronosd is useless. 

**The issue is still there.**

@yihuang Please help to check, thx.

**Comment by huahuayu** [comment] 2022-05-21 08:34
What's the problem do you think, I am willing to dig into the issue, please share your findings.

**Comment by huahuayu** [comment] 2022-05-22 07:48
## My findings

In `tendermint/state/txindex/indexer_service.go` use unbuffered channel for blockHead and tx subscribe, which may block the channel

```go
	blockHeadersSub, err := is.eventBus.SubscribeUnbuffered(
		context.Background(),
		subscriber,
		types.EventQueryNewBlockHeader)
	if err != nil {
		return err
	}

	txsSub, err := is.eventBus.SubscribeUnbuffered(context.Background(), subscriber, types.EventQueryTx)
	if err != nil {
		return err
	}
```

In `tendermint/libs/pubsub/pubsub.go` I do observed send event msg get blocked, the logic goes to `-->` mark.

```go
func (state *state) send(msg interface{}, events map[string][]string) error {
	for qStr, clientSubscriptions := range state.subscriptions {
		q := state.queries[qStr].q

		match, err := q.Matches(events)
		if err != nil {
			return fmt.Errorf("failed to match against query %s: %w", q.String(), err)
		}

		if match {
			for clientID, subscription := range clientSubscriptions {
				if cap(subscription.out) == 0 {
					// block on unbuffered channel
-->					subscription.out <- NewMessage(msg, events)
				} else {
					// don't block on buffered channels
					select {
					case subscription.out <- NewMessage(msg, events):
					default:
						state.remove(clientID, qStr, ErrOutOfCapacity)
					}
				}
			}
		}
	}

	return nil
}
```

## Solution

I changed `blockHeadersSub, err := is.eventBus.SubscribeUnbuffered` and `txsSub, err := is.eventBus.SubscribeUnbuffered` to buffered channel, so far so good, let me keep observing for a while.

**Comment by huahuayu** [comment] 2022-05-24 08:17
Three days passed, still works. @yihuang

**Comment by yihuang** [comment] 2022-05-24 08:20
> Three days passed, still works. @yihuang

awsome, so the issue is dead lock on unbuffered channel?

**Comment by huahuayu** [comment] 2022-05-24 11:11
I don't know how to effectively reproduce the issue and am not sure if there are other side effects.

**Comment by yihuang** [comment] 2022-09-27 02:03
I think ws server issue will eventually be fixed by this solution:https://github.com/crypto-org-chain/cronos/issues/665

**Closed by yihuang** 2022-09-27 02:03 UTC
