### ISSUE TITLE
Websocket blocks after terminating without unsubscribing

### ISSUE THREAD

**Issue by samuel-tay** [crypto-org-chain/cronos#207] opened 2021-11-08 15:10 UTC
**Describe the bug**
As discussed on Discord https://discord.com/channels/783264383978569728/783264902613565450/907267013028749322

It was discovered that subscribing to WS works.

However, if a subscription is not unsubscribed and the session is terminated, then the WS blocks up and no further requests will be entertained. It doesn't help to reconnect and unsubscribe.

Also, in the instance where 2 clients are connected and if Client A terminates the session without unsubscribing, Client B blocks as well, and the whole WS blocks.

**To Reproduce**
1. Have a local node running
2. On CLI `wscat -c ws://localhost:8546` (response connected)
3. `{"jsonrpc":"2.0", "id": 1, "method": "eth_subscribe", "params": ["newPendingTransactions"]}` (respond with suscription id)
4. Ctrl+C to force exit
5. Repeat 2-3, **no response** in step 3
6. Restart node
7. Repeat steps 2-3
8. `{"id": 1, "method": "eth_unsubscribe", "params": ["(subscriptionid)"]}`
9. Ctrl+C to exit.
10. Repeat steps 2-3, subscription works

**Expected behavior**
WS should handle disconnection without blocking.

**Screenshots**
NA

**Desktop (please complete the following information):**
Node is Linux

**Comment by tomtau** [comment] 2021-11-09 03:52
this is more likely an issue on Ethermint, I assume: https://github.com/tharsis/ethermint/issues/new?assignees=&labels=&template=bug-report.md
@thomas-nguy @yihuang

**Comment by odeke-em** [comment] 2022-02-09 16:40
@yihuang and @thomas-nguy I found the cause of the issue in Ethermint per https://github.com/tharsis/ethermint/issues/821#issuecomment-1033959984 and it comes from a sync.RWMutex .Lock() being invoked before a .Runlock() is invoked and Go's docs for sync.RWMutex explicitly call out this problem per https://pkg.go.dev/sync#RWMutex
<img width="1156" alt="Screen Shot 2022-02-09 at 4 27 33 PM" src="https://user-images.githubusercontent.com/4898263/153245512-c4a3e20a-9bb5-44a0-9902-633990a63f87.png">

It'll be fixed shortly in Ethermint.

**Comment by odeke-em** [comment] 2022-02-10 22:59
The fixing PR got merged per https://github.com/tharsis/ethermint/pull/933 Can we please close this issue?

**Comment by samuel-tay** [comment] 2022-02-10 23:18
Thanks for this! @odeke-em

**Comment by odeke-em** [comment] 2022-02-10 23:19
> Thanks for this! @odeke-em 

Cheers, and thank you @samuel-tay!

**Closed** 2022-02-10 23:18 UTC
