### ISSUE TITLE
Not able to get Block data from archive node

### ISSUE THREAD

**Issue by suyog-unmarshal** [crypto-org-chain/cronos#422] opened 2022-04-08 10:16 UTC
**Describe the bug**
running an archive node, and the node is in sync.  when i make rpc call to get block data its giving error
**To Reproduce**
1 -> Have a synced archive node (snapshot from https://quicksync.io/networks/crypto.html)
2 -> POST request to rpc endpoint with body `{"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["0x1A50FB", false],"id":83}`

**Expected behavior**
to get Block details

**Error result**
`{
    "jsonrpc": "2.0",
    "id": 83,
    "error": {
        "code": -32000,
        "message": "rpc error: code = Unknown desc = panic message redacted to hide potentially sensitive system info: panic"
    }
}`

**Screenshots**
<img width="838" alt="image" src="https://user-images.githubusercontent.com/88375823/162415274-e8a8e988-a8e6-42d4-b364-0419d0c81a64.png">

**Desktop (please complete the following information):**
 - OS: Amazon Linux 2 AMI
 - Version: 0.6.5

**Comment by yihuang** [comment] 2022-04-08 13:49
I think you are request for block which haven't synced yet?

**Comment by yihuang** [comment] 2022-04-19 09:46
I assume the issue is fixed after node catch up on syncing, closing now, feel free to reopen if the issue is not fixed

**Closed by yihuang** 2022-04-19 09:46 UTC
